-- ============================================
-- TimetablePro Seed Data
-- NOTE: Use `node db/init.js` for proper bcrypt
-- password hashing. This file is for reference
-- and Docker initialization.
-- Default password for all accounts: password123
-- ============================================

-- Users (password hashes generated by db/init.js)
-- The hashes below are bcrypt($2b$10$) for 'password123'
INSERT INTO users (name, email, password_hash, role, level) VALUES
  ('Admin User', 'admin@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'admin', NULL),
  ('Dr. James Okon', 'hod@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'hod', NULL),
  ('Dr. Mary Bassey', 'lecturer1@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'lecturer', NULL),
  ('Mr. John Edet', 'lecturer2@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'lecturer', NULL),
  ('Dr. Grace Akpan', 'lecturer3@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'lecturer', NULL),
  ('Blessing Udo', 'student1@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'student', 100),
  ('Emmanuel Obi', 'student2@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'student', 100),
  ('Favour Inyang', 'student3@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'student', 100),
  ('Daniel Etim', 'student4@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'student', 200),
  ('Sarah Ndem', 'student5@unicross.edu.ng', '$2a$10$rAuXhrETzgCOmBdiXloL/eL.fExn6qn2WU4diKMXH8a.gcHcyoCty', 'student', 200);

-- Lecturers (linked to user accounts)
INSERT INTO lecturers (user_id, availability_notes) VALUES
  (3, 'Available Monday to Friday, 8AM-4PM'),
  (4, 'Not available on Wednesdays'),
  (5, 'Available all weekdays');

-- Venues
INSERT INTO venues (name, capacity) VALUES
  ('Lecture Theatre 1', 200),
  ('Lecture Theatre 2', 150),
  ('Computer Room 1', 100),
  ('Computer Room 2', 40);

-- Time Slots (Monday-Friday, 4 slots per day = 20 total)
INSERT INTO time_slots (day, start_time, end_time) VALUES
  ('Monday', '08:00:00', '10:00:00'),
  ('Monday', '10:00:00', '12:00:00'),
  ('Monday', '12:00:00', '14:00:00'),
  ('Monday', '14:00:00', '16:00:00'),
  ('Tuesday', '08:00:00', '10:00:00'),
  ('Tuesday', '10:00:00', '12:00:00'),
  ('Tuesday', '12:00:00', '14:00:00'),
  ('Tuesday', '14:00:00', '16:00:00'),
  ('Wednesday', '08:00:00', '10:00:00'),
  ('Wednesday', '10:00:00', '12:00:00'),
  ('Wednesday', '12:00:00', '14:00:00'),
  ('Wednesday', '14:00:00', '16:00:00'),
  ('Thursday', '08:00:00', '10:00:00'),
  ('Thursday', '10:00:00', '12:00:00'),
  ('Thursday', '12:00:00', '14:00:00'),
  ('Thursday', '14:00:00', '16:00:00'),
  ('Friday', '08:00:00', '10:00:00'),
  ('Friday', '10:00:00', '12:00:00'),
  ('Friday', '12:00:00', '14:00:00'),
  ('Friday', '14:00:00', '16:00:00');

-- Courses (8 courses across Level 100 and Level 200)
INSERT INTO courses (code, title, unit, level, lecturer_id, expected_students) VALUES
  ('CMP101', 'Introduction to Computer Science', 3, 100, 1, 150),
  ('CMP102', 'Programming Fundamentals', 3, 100, 2, 120),
  ('CMP103', 'Computer Hardware', 2, 100, 3, 130),
  ('CMP104', 'Mathematics for Computing', 3, 100, 1, 140),
  ('CMP201', 'Data Structures and Algorithms', 3, 200, 2, 80),
  ('CMP202', 'Database Management Systems', 3, 200, 3, 90),
  ('CMP203', 'Web Development', 2, 200, 1, 85),
  ('CMP204', 'Operating Systems', 3, 200, 2, 75);
